const fs = require('fs')
const path = require('path')

const envPath = path.resolve(__dirname, '..', '.env')
let agentKey = process.env.AGENT_SECRET_KEY || process.env.AGENT_SECRET || ''

if (!agentKey && fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8')
  const match = content.match(/^AGENT_SECRET_KEY=(.+)$/m) || content.match(/^AGENT_SECRET=(.+)$/m)
  if (match) {
    agentKey = match[1].trim()
  }
}

if (!agentKey) {
  const provPath = path.join(__dirname, 'Provisioning.cs')
  if (fs.existsSync(provPath)) {
    console.log('[PROVISIONING] Reusing existing Provisioning.cs')
    process.exit(0)
  }
  console.error('[ERROR] AGENT_SECRET_KEY not found in environment or backend/.env')
  process.exit(1)
}

const salt = [0x5A, 0x3C, 0x7E, 0x1F, 0x4B, 0x6D, 0x2A, 0x8C]
const keyBytes = Buffer.from(agentKey, 'utf8')
const obfuscated = []
for (let i = 0; i < keyBytes.length; i++) {
  obfuscated.push('0x' + (keyBytes[i] ^ salt[i % salt.length]).toString(16).padStart(2, '0'))
}

const provCsContent = `// Auto-generated by generate_provisioning.cjs during build - DO NOT COMMIT TO GIT
namespace XBuddyPrintStation
{
    internal static class Provisioning
    {
        private static readonly byte[] Salt = new byte[] { 0x5a, 0x3c, 0x7e, 0x1f, 0x4b, 0x6d, 0x2a, 0x8c };
        private static readonly byte[] ObfuscatedKey = new byte[] {
            ${obfuscated.join(', ')}
        };

        public static string GetAgentSecretKey()
        {
            byte[] decrypted = new byte[ObfuscatedKey.Length];
            for (int i = 0; i < ObfuscatedKey.Length; i++)
            {
                decrypted[i] = (byte)(ObfuscatedKey[i] ^ Salt[i % Salt.Length]);
            }
            return System.Text.Encoding.UTF8.GetString(decrypted);
        }
    }
}
`

const outPath = path.join(__dirname, 'Provisioning.cs')
fs.writeFileSync(outPath, provCsContent, 'utf8')
console.log(`[PROVISIONING] Generated ${outPath} (Obfuscated key payload: ${keyBytes.length} bytes)`)
